name: Pruebas Orange HRMDemo con Cypress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      navegador:
        description: 'Selecciona el navegador'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
      usuario:
        description: 'Usuario'
        required: true
        default: 'Admin'
      password:
        description: 'Password'
        required: true
        default: 'admin123'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: Ejecutar Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ github.event.inputs.navegador || 'chrome' }}
        env:
          CYPRESS_USER_NAME: ${{ github.event.inputs.usuario || 'Admin' }}
          CYPRESS_USER_PASS: ${{ github.event.inputs.password || 'admin123' }}

      - name: Generar Resumen
        if: always() 
        run: |
          echo "### ðŸ“Š Resumen de EjecuciÃ³n" >> $GITHUB_STEP_SUMMARY
          echo "- **Navegador:** ${{ github.event.inputs.navegador || 'chrome' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Usuario enviado:** ${{ github.event.inputs.usuario || 'Admin' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Resultado:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY